### ISSUE TITLE
Flat-fact has incorrect dates for NeXT founding + acquisition?

### ISSUE THREAD

**Issue by kenmhaggerty** [learn-co-curriculum/reading-ios-things-nsstring-can-do#12]
Wikipedia says that NeXT was founded in 1985 and acquired by Apple in 1996: https://en.wikipedia.org/wiki/NeXT

**Comment by markedwardmurray** [comment]
"Apple Computer announced an intention to acquire NeXT on December 20, 1996.[2] Apple paid $429 million in cash, which went to the initial investors and 1.5 million Apple shares, which went to Steve Jobs, who was deliberately not given cash for his part in the deal.[2][53] The main purpose of the acquisition was to use NeXTSTEP as a foundation to replace the dated Mac OS, instead of BeOS or the in-development Copland.[54] The deal was finalized on February 7, 1997,[55] bringing Jobs back to Apple as a consultant, who was later appointed as interim CEO.[56] In 2000 Jobs took the CEO position as a permanent assignment."
